In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

from sklearn.metrics import classification_report, roc_auc_score

In [2]:
df = pd.read_csv('../data/processed/churn_engineered.csv')

In [3]:
X = df.drop(columns=['Churn'])
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [4]:
print(y.value_counts(normalize=True))

Churn
0    0.73463
1    0.26537
Name: proportion, dtype: float64

In [5]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Model evaluation without handling Class Imbalance
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1035
           1       0.65      0.52      0.58       374

    accuracy                           0.80      1409

AUC: 0.8439639360355473

## Class Imbalance handling techniques

1. Class Weighting

In [6]:
model_balanced = LogisticRegression(class_weight='balanced')
model_balanced.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced')

2. Oversampling: SMOTE

In [7]:
smote = SMOTE(random_state = 42)

X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

print(y_train_smote.value_counts())   # should now be ~50/50

Churn
0    4139
1    4139
Name: count, dtype: int64

In [8]:
model_smote = LogisticRegression()
model_smote.fit(X_train_smote, y_train_smote)

LogisticRegression()

3. Random Undersampling

In [9]:
undersampler = RandomUnderSampler(random_state=42)

X_train_under, y_train_under = undersampler.fit_resample(X_train_scaled, y_train)

print(y_train_under.value_counts())   # ~50/50, but much smaller total

Churn
0    1495
1    1495
Name: count, dtype: int64

In [10]:
model_under = LogisticRegression()
model_under.fit(X_train_under, y_train_under)

LogisticRegression()

### evaluate which imbalance handling technique is better

In [11]:
def evaluate(model, name):
    y_pred = model.predict(X_test_scaled)
    y_proba = model.predict_proba(X_test_scaled)[:, 1]
    print(f"---{name}---")
    print(classification_report(y_test, y_pred))
    print("AUC:", roc_auc_score(y_test, y_proba))
    print()

evaluate(model_balanced, "class_weight=balanced")
evaluate(model_smote, "SMOTE")
evaluate(model_under, "Undersampling")

---class_weight=balanced---
              precision    recall  f1-score   support

           0       0.91      0.72      0.80      1035
           1       0.51      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.76      1409

AUC: 0.8439200186003255

---SMOTE---
              precision    recall  f1-score   support

           0       0.91      0.72      0.80      1035
           1       0.51      0.79      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.75      1409

AUC: 0.8423803249890206

---Undersampling---
              precision    recall  f1-score   support

           0       0.91      0.72      0.80      1035
           1       0.51      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.76      1409

AUC: 0.8452117078715545

- 3 methods were explored to handle class imbalance: class weighting, SMOTE, undersampling
- all 3 methods worked almost identically well. each one roughly doubled how much actual churners the model catches(0.52 to ~0.80) but false alarms also increased.

- missing a real churner is more harmful for a business than a false alarm so catching so class imbalance handling is done.

- class weighting is picked as it performed just as well as the other 2 methods and is the simplest.

# Model Comparisions

Training Decision tree, random forest and XG boost

In [19]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.pipeline import make_pipeline

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [ ]:
log_reg = make_pipeline(
    StandardScaler(),
    LogisticRegression(
        class_weight='balanced',
        max_iter=1000,
        random_state=42
    )
)

rf = RandomForestClassifier(
    class_weight='balanced',
    random_state=42
)

scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

xgb = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state= 42,
    eval_metric='logloss'
)

In [14]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [16]:
log_reg_score = cross_val_score(
    log_reg, X_train, y_train,
    cv=cv,
    scoring='roc_auc'
)

rf_score = cross_val_score(
    rf, X_train, y_train,
    cv=cv,
    scoring='roc_auc'
)

xgb_score = cross_val_score(
    xgb, X_train, y_train,
    cv=cv,
    scoring='roc_auc'
)

print("Logistic Regression AUC:",
      log_reg_score.mean(), "+/-", log_reg_score.std())

print("Random Forest AUC:",
      rf_score.mean(), "+/-", rf_score.std())

print("XGBoost AUC:",
      xgb_score.mean(), "+/-", xgb_score.std())

Logistic Regression AUC: 0.8477928734559278 +/- 0.011146628108891714
Random Forest AUC: 0.8260714521341791 +/- 0.010864574788645127
XGBoost AUC: 0.8246143303131233 +/- 0.005488754208753645

In [18]:
cv_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],
    "Mean AUC": [
        log_reg_score.mean(),
        rf_score.mean(),
        xgb_score.mean()
    ],
    "Std AUC": [
        log_reg_score.std(),
        rf_score.std(),
        xgb_score.std()
    ]
})

display(cv_results.round(4))

best_name = cv_results.loc[
    cv_results["Mean AUC"].idxmax(), "Model"
]

print("Best model: ", best_name)

                 Model  Mean AUC  Std AUC
0  Logistic Regression    0.8478   0.0111
1        Random Forest    0.8261   0.0109
2              XGBoost    0.8246   0.0055

Best model:  Logistic Regression

In [23]:
param_grid = {
    'logisticregression__C': [0.01, 0.1, 1, 10, 100],
    'logisticregression__l1_ratio': [0.0, 1.0]
}

grid_search = GridSearchCV(
    estimator=make_pipeline(
        StandardScaler(),
        LogisticRegression(
            class_weight='balanced',
            solver='liblinear',
            max_iter=1000,
            random_state=42
        )
    ),
    param_grid=param_grid,
    cv=cv,
    scoring='roc_auc',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best parameters:", grid_search.best_params_)
print("Best CV ROC-AUC:", grid_search.best_score_)

Best parameters: {'logisticregression__C': 0.1, 'logisticregression__l1_ratio': 1.0}
Best CV ROC-AUC: 0.8479944886161241

In [24]:
log_reg_tuned = grid_search.best_estimator_

print(log_reg_tuned)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression',
                 LogisticRegression(C=0.1, class_weight='balanced',
                                    l1_ratio=1.0, max_iter=1000,
                                    random_state=42, solver='liblinear'))])

In [26]:

log_reg.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [27]:
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [28]:
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [29]:
from sklearn.metrics import (
    classification_report,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

models = {
    "Logistic Regression": log_reg,
    "Random Forest": rf,
    "XGBoost": xgb,
    "Tuned Logistic Regression": log_reg_tuned
}

results = []

for name, model in models.items():

    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    print(f"\n--- {name} ---")
    print(classification_report(y_test, y_pred))

    results.append({
        "Model": name,
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_proba)
    })

comparison_df = pd.DataFrame(results)

display(comparison_df.round(4))

--- Logistic Regression ---
              precision    recall  f1-score   support

           0       0.91      0.72      0.80      1035
           1       0.51      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.76      1409


--- Random Forest ---
              precision    recall  f1-score   support

           0       0.86      0.81      0.84      1035
           1       0.55      0.64      0.59       374

    accuracy                           0.77      1409
   macro avg       0.71      0.72      0.71      1409
weighted avg       0.78      0.77      0.77      1409


--- XGBoost ---
              precision    recall  f1-score   support

           0       0.87      0.79      0.83      1035
           1       0.54      0.68      0.61       374

    accuracy                           0.76      1409
   macro avg       0.71      0.74      0.72      1409
weighted avg       0.79      0.76      0.77      1409


--- Tuned Logistic Regression ---
              precision    recall  f1-score   support

           0       0.91      0.72      0.80      1035
           1       0.51      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.75      1409

                       Model  Precision  Recall      F1  ROC-AUC
0        Logistic Regression     0.5085  0.8021  0.6224   0.8439
1              Random Forest     0.5497  0.6364  0.5898   0.8204
2                    XGBoost     0.5435  0.6845  0.6059   0.8228
3  Tuned Logistic Regression     0.5059  0.7995  0.6197   0.8451

### Conclusion

Logistic Regression, Random Forest, and XGBoost were compared using 5-fold stratified cross-validation. Logistic Regression performed best and was tuned using GridSearchCV. Although tuning slightly improved test ROC-AUC from 0.8439 to 0.8451, it reduced recall and F1-score. The original Logistic Regression was retained because it achieved the highest recall (0.8021) and F1-score (0.6224), providing a better balance between detecting churners and minimizing false alerts, with nearly identical ranking performance.